### ISSUE TITLE
Poster loading text without translation

### ISSUE THREAD

**Issue by Mondmarmelade** [Bergflix-Remake/bergflix#22]
At line 26:
https://github.com/Bergflix-Remake/bergflix/blob/b14772f5000a19886075d297b6a80293330053c5/src/components/Poster/Poster.svelte#L23-L27

**Comment by AnnikenYT** [comment]
Meine mich zu erinnern das absichtlich so zu lassen, und stattdessen bei usage eine Translation reinzupassen. Aber ein default wäre gut.

**Comment by AnnikenYT** [comment]
Obwohl; Evtl. kann man das auch so lassen, da nicht immer beim Laden ein fester Status zum Anzeigen vorhanden ist.

**Comment by Mondmarmelade** [comment]
Okay, good to know.
Ich hatte es extra nicht als Bug deklariert, weil ich mir nicht sicher war ob es absichtlich so ist! 👍🏼
